services:
  app:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=MensShop
    ports:
       - "7777:7777"
    depends_on:
       - db
  db:
    container_name: app_test
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MensShop
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432" # HaMeHeHO wa 5432
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  db: