server:
  port: 7777

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2005b
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
token:
  sign:
    secret-key: CKXEDQBVK